name: Dashboard CD

on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror-to-epitech:
    name: Déploiement du Code
    runs-on: ubuntu-latest

    steps:
      - name: Vérification des secrets
        shell: bash
        run: |
          if [ -z "${{ secrets.GIT_DASHBOARD_REPO }}" ]; then
            echo "Erreur: le secret GIT_DASHBOARD_REPO est vide ou introuvable."
            exit 1
          fi
          echo "Succès: le secret existe."

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirroring step
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.GIT_DASHBOARD_REPO }}
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_DASHBOARD_SECRET }}